"""Regenerate the static reference. Maintenance dependency: Markdown==3.10.2."""
from pathlib import Path
import argparse
import html
import re
import markdown

ROOT = Path(__file__).resolve().parents[1]
IDS = 'why concepts example evidence atoms linking attempts outcomes recovery usage performance boundaries faq'.split()
LABELS = {
    'en': ['Why a task graph', 'Four objects', 'Complete example', 'Source evidence', 'Session → Atom', 'Atom → Task', 'Task and Attempt', 'Outcomes and feedback', 'Persistence and recovery', 'Usage and cost', 'Performance', 'Current boundaries', 'FAQ'],
    'zh': ['为什么需要任务图', '四个核心对象', '完整示例', '来源与证据', 'Session → Atom', 'Atom → Task', 'Task 与 Attempt', '结果与反馈', '保存与恢复', '用量与成本', '性能边界', '当前能力边界', '常见问题'],
}

def bilingual(en, zh):
    return f'<span data-doc-lang="en">{html.escape(en)}</span><span data-doc-lang="zh">{html.escape(zh)}</span>'

def render_body(text, lang):
    rendered = markdown.markdown(text, extensions=['tables', 'fenced_code'])
    label = 'Scrollable reference table' if lang == 'en' else '可横向滚动的参考表格'
    rendered = rendered.replace('<table>', f'<div class="task-table" tabindex="0" role="region" aria-label="{label}"><table class="doc-table">').replace('</table>', '</table></div>')
    return f'<div data-doc-lang="{lang}">{rendered}</div>'

def render():
    sources = {}
    for lang in ('en', 'zh'):
        text = (ROOT / f'docs/architecture/session-task-attempt.{lang}.md').read_text()
        intro, *parts = re.split(r'^## ', text, flags=re.M)
        assert len(parts) == len(IDS), 'Both translations must contain the same 13 sections'
        sources[lang] = (intro.split('\n', 1)[1], [part.split('\n', 1) for part in parts])
    nav = ''.join(f'<a href="#{key}">{bilingual(LABELS["en"][i], LABELS["zh"][i])}</a>' for i, key in enumerate(IDS))
    intro = ''.join(render_body(sources[lang][0], lang) for lang in sources)
    sections = []
    figures = {
        'concepts': ('model', 'One session can contribute to several tasks; a task can have several attempts. Arrows illustrate relationships, not a one-to-one conversion.', '一个 Session 可以涉及多个 Task，一个 Task 可以包含多个 Attempt。箭头表示引用关系，并非一对一转换。'),
        'linking': ('flow', 'Normalize and segment evidence before goal linking; group attempts before publishing the graph.', '先规范化并切分证据，再关联用户目标；组织执行尝试后发布任务图。'),
        'recovery': ('recovery', 'Validate a new generation before switching the visible pointer. Queue acknowledgements preserve concurrently arriving work.', '校验新一代数据后才切换可见指针；队列确认保留处理期间新增的工作。'),
    }
    for i, key in enumerate(IDS):
        heading = bilingual(*(sources[lang][1][i][0] for lang in sources))
        body = ''.join(render_body(sources[lang][1][i][1], lang) for lang in sources)
        if key in figures:
            name, en, zh = figures[key]
            body += '<figure>'
            for lang, caption in [('en', en), ('zh', zh)]:
                body += f'<div data-doc-lang="{lang}"><div class="task-diagram" tabindex="0" role="region" aria-label="{html.escape(caption)}"><img src="assets/task-graph-{name}.svg" alt="{html.escape(caption)}" loading="lazy"></div><figcaption class="task-caption">{html.escape(caption)}</figcaption></div>'
            body += '<p class="task-caption task-scroll-hint">' + bilingual('On narrow screens, scroll the diagram sideways to see all relationships.', '小屏幕可左右滑动结构图，查看完整关系。') + '</p></figure>'
        sections.append(f'<section id="{key}" class="doc-sec {"task-status" if key == "boundaries" else ""}"><h2>{heading}</h2>{body}</section>')
    return f'''<!DOCTYPE html>
<!-- Generated by scripts/render_task_graph_docs.py; edit docs/architecture/*.md. -->
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Session, Atom, Task and Attempt · xskill Wiki</title>
<meta name="description" content="How xskill organizes session evidence into tasks and execution attempts: object model, linking, outcomes, persistence, recovery and current boundaries.">
<link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="task-graph.css"></head>
<body data-title-key="tg.title">
<a class="skip-link" href="#reference">{bilingual('Skip to reference', '跳到正文')}</a>
<header class="nav-wrap"><nav class="nav"><a class="brand" href="index.html"><span class="brand__coco">🥥</span><span class="brand__name">xskill<span class="brand__dot">.wiki</span></span></a><ul class="nav__links"><li><a href="wiki.html">Wiki</a></li></ul><div class="nav__actions"><div class="lang" role="group" aria-label="Language / 语言"><button class="lang__btn" type="button" data-set-lang="en">EN</button><button class="lang__btn" type="button" data-set-lang="zh">中</button></div></div></nav></header>
<section class="wiki-hero task-hero"><div class="wiki-hero__inner"><div class="task-breadcrumb"><a href="wiki.html">Wiki</a> / {bilingual('Architecture reference', '架构参考')}</div><span class="kicker">Session → Atom → Task → Attempt</span><h1>{bilingual('From sessions to tasks and attempts', '从会话到任务与执行尝试')}</h1><p class="section__sub">{bilingual('Follow the evidence, understand goal identity, and trace each execution.', '沿着证据理解用户目标，追溯每一次执行。')}</p><div class="task-meta"><span>{bilingual('Checked: September 12, 2026', '实现核对：2026 年 9 月 12 日')}</span><span>{bilingual('Current behavior and known boundaries', '当前实现与已知边界')}</span></div></div></section>
<div class="wiki-shell task-shell"><aside class="wiki-toc"><div class="wiki-toc__card"><h4>{bilingual('On this page', '本页目录')}</h4><nav aria-label="Contents / 目录">{nav}</nav></div></aside><main id="reference"><section class="doc-sec"><h2>{bilingual('Overview', '方案概览')}</h2>{intro}</section>{''.join(sections)}</main></div>
<footer class="task-footer">{bilingual('Documentation sources', '文档源文件')} · <a href="docs/architecture/session-task-attempt.en.md">English Markdown</a> · <a href="docs/architecture/session-task-attempt.zh.md">中文 Markdown</a> · <a href="wiki.html">Wiki</a></footer><script src="i18n.js"></script><script src="wiki.js"></script></body></html>
'''

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = ROOT / 'task-graph.html'
    output = render()
    if args.check:
        assert target.read_text() == output, 'Regenerate task-graph.html'
        print('Generated page matches both Markdown sources')
    else:
        target.write_text(output)
